<?php
namespace gamboamartin\cat_sat\models;
use base\orm\modelo;
use gamboamartin\direccion_postal\models\dp_pais;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class cat_sat_moneda extends modelo{
    public function __construct(PDO $link){
        $tabla = 'cat_sat_moneda';
        $columnas = array($tabla=>false,"dp_pais"=>$tabla);
        $campos_obligatorios[] = 'descripcion';
        $campos_obligatorios[] = 'dp_pais_id';

        $tipo_campos = array();
        $tipo_campos['codigo'] = 'cod_3_letras_mayusc';
        $tipo_campos['dp_pais_id'] = 'id';


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, tipo_campos: $tipo_campos);
    }

    public function alta_bd(): array|stdClass
    {
        if(!isset($this->registro['dp_pais_id']) || $this->registro['dp_pais_id'] === -1){
            $id_predeterminado = (new dp_pais($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener pais predeterminado', data: $id_predeterminado);
            }
            $this->registro['dp_pais_id'] = $id_predeterminado;
        }


        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta registro', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }
}