<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\cat_sat\controllers;

use base\controller\controler;
use gamboamartin\cat_sat\models\cat_sat_conf_imps;
use gamboamartin\cat_sat\models\cat_sat_traslado_conf;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use html\cat_sat_conf_imps_html;
use html\cat_sat_factor_html;
use html\cat_sat_tipo_factor_html;
use html\cat_sat_tipo_impuesto_html;
use html\cat_sat_traslado_conf_html;
use PDO;
use stdClass;

class controlador_cat_sat_traslado_conf extends _cat_sat_base {

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){

        $modelo = new cat_sat_traslado_conf(link: $link);
        $html_ = new cat_sat_traslado_conf_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id:$this->registro_id);

        $datatables = $this->init_datatable();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable', data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $configuraciones = $this->init_configuraciones();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar configuraciones', data: $configuraciones);
            print_r($error);
            die('Error');
        }
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:  $ws);
        }

        $cat_sat_conf_imps_id = (new cat_sat_conf_imps_html(html: $this->html_base))->select_cat_sat_conf_imps_id(
            cols: 12,con_registros:  true,id_selected:  -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_conf_imps_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_conf_imps_id = $cat_sat_conf_imps_id;

        $cat_sat_factor_id = (new cat_sat_factor_html(html: $this->html_base))->select_cat_sat_factor_id(
            cols: 4,con_registros:  true,id_selected:  -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_factor_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_factor_id = $cat_sat_factor_id;

        $cat_sat_tipo_factor_id = (new cat_sat_tipo_factor_html(html: $this->html_base))->select_cat_sat_tipo_factor_id(
            cols: 4,con_registros:  true,id_selected:  -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_tipo_factor_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_tipo_factor_id = $cat_sat_tipo_factor_id;

        $cat_sat_tipo_impuesto_id = (new cat_sat_tipo_impuesto_html(html: $this->html_base))->select_cat_sat_tipo_impuesto_id(
            cols: 4,con_registros:  true,id_selected:  -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_tipo_impuesto_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_tipo_impuesto_id = $cat_sat_tipo_impuesto_id;


        return $r_alta;
    }


    private function init_configuraciones(): controler
    {
        $this->titulo_lista = 'Registro de Configuraciones de Traslados';

        $this->lista_get_data = true;

        return $this;
    }

    /**
     * Inicializa los elementos para datatable
     * @return stdClass
     * @version 7.32.1
     */
    private function init_datatable(): stdClass
    {
        $columns["cat_sat_traslado_conf_id"]["titulo"] = "Id";
        $columns["cat_sat_traslado_conf_codigo"]["titulo"] = "Código";
        $columns["cat_sat_traslado_conf_descripcion"]["titulo"] = "Configuraciones";

        $filtro = array("cat_sat_traslado_conf.id","cat_sat_traslado_conf.codigo","cat_sat_traslado_conf.descripcion");

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }

    protected function key_selects_txt(array $keys_selects): array
    {
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 4, key: 'codigo',
            keys_selects: $keys_selects, place_holder: 'Código');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 8, key: 'descripcion',
            keys_selects: $keys_selects, place_holder: 'Conf de Impuestos');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        return $keys_selects;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $r_modifica = $this->init_modifica();
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al generar salida de template', data: $r_modifica, header: $header, ws: $ws);
        }

        $base = $this->base_upd(keys_selects: array(), params: array(), params_ajustados: array());
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al integrar base', data: $base, header: $header, ws: $ws);
        }

        $cat_sat_conf_imps_id = (new cat_sat_conf_imps_html(html: $this->html_base))->select_cat_sat_conf_imps_id(
            cols: 12,con_registros:  true,id_selected:  $this->row_upd->cat_sat_conf_imps_id,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_conf_imps_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_conf_imps_id = $cat_sat_conf_imps_id;

        $cat_sat_factor_id = (new cat_sat_factor_html(html: $this->html_base))->select_cat_sat_factor_id(
            cols: 4,con_registros:  true,id_selected:  $this->row_upd->cat_sat_factor_id,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_factor_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_factor_id = $cat_sat_factor_id;

        $cat_sat_tipo_factor_id = (new cat_sat_tipo_factor_html(html: $this->html_base))->select_cat_sat_tipo_factor_id(
            cols: 4,con_registros:  true,id_selected:  $this->row_upd->cat_sat_tipo_factor_id,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_tipo_factor_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_tipo_factor_id = $cat_sat_tipo_factor_id;

        $cat_sat_tipo_impuesto_id = (new cat_sat_tipo_impuesto_html(html: $this->html_base))->select_cat_sat_tipo_impuesto_id(
            cols: 4,con_registros:  true,id_selected:  $this->row_upd->cat_sat_tipo_impuesto_id,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_tipo_impuesto_id,
                header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_tipo_impuesto_id = $cat_sat_tipo_impuesto_id;


        return $r_modifica;
    }
}