<?php include "templates/inputs/modifica/id.php"; ?>
<?php include "templates/inputs/modifica/codigo.php"; ?>
<?php include "templates/inputs/modifica/codigo_bis.php"; ?>
<?php include "templates/inputs/modifica/descripcion.php"; ?>
<?php include "templates/inputs/modifica/alias.php"; ?>
<?php include "templates/inputs/modifica/descripcion_select.php"; ?>
<?php include "templates/botons/cat_sat_tipo_persona/valida_persona_fisica.php"; ?>
<?php include "templates/botons/status.php"; ?>
<?php include "templates/botons/submit/modifica_bd.php"; ?>
